"""Explicit, target-scoped inventory of preparation evidence; no data or model loads."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from src.research.io import safe_path

# A book catalogue change must not invalidate the independent model-study packet.
ARTIFACTS: dict[str, tuple[str, str]] = {
    "study_design": ("common", "configs/research/study_design.json"),
    "preparation_status": ("common", "configs/research/preparation.json"),
    "research_index": ("common", "docs/research/README.md"),
    "study_decisions": ("common", "docs/research/study_decisions.md"),
    "evaluation_protocol": ("common", "docs/eval_protocol.md"),
    "preflight_contract": ("common", "src/research/preparation.py"),
    "file_integrity_contract": ("common", "src/research/io.py"),
    "manifest_contract": ("common", "src/research/manifest.py"),
    "research_entry": ("common", "scripts/research.py"),
    "builder_location": ("common", "src/research/builders/__init__.py"),
    "model_literature": ("model_study", "research/preparation/model_literature.json"),
    "model_methods_review": ("model_study", "docs/research/model_recipe_review.md"),
    "backbone_candidates": ("model_study", "research/preparation/backbone_candidates.json"),
    "backbone_review": ("model_study", "docs/research/backbone_interface_review.md"),
    "repository_metadata": ("model_study", "research/preparation/repository_metadata.json"),
    "data_inventory": ("archive", "research/preparation/data_inventory.json"),
    "data_audit": ("archive", "research/preparation/data_audit.json"),
    "data_auditor": ("archive", "src/research/builders/data_audit.py"),
    "bgc_candidate": ("model_study", "research/preparation/bgc_candidate_manifest.json"),
    "bgc_builder": ("model_study", "src/research/builders/bgc_source.py"),
    "bgc_groups": ("model_study", "research/preparation/bgc_group_manifest.json"),
    "bgc_group_builder": ("model_study", "src/research/builders/bgc_groups.py"),
    "book_group_contract": ("model_study", "src/research/book_groups.py"),
    "book_field_mapping": ("model_study", "research/preparation/book_field_mapping.json"),
    "book_fields": ("model_study", "research/preparation/book_field_manifest.json"),
    "book_field_builder": ("model_study", "src/research/builders/book_fields.py"),
    "book_field_contract": ("model_study", "src/research/book_fields.py"),
    "book_group_review": ("model_study", "research/preparation/book_group_review.json"),
    "book_group_reviewer": ("model_study", "src/research/builders/book_groups_review.py"),
    "book_field_review": ("model_study", "research/preparation/book_field_review.json"),
    "book_field_review_report": (
        "model_study",
        "research/preparation/book_field_review_manifest.json",
    ),
    "book_field_reviewer": ("model_study", "src/research/builders/field_review.py"),
    "book_field_review_contract": ("model_study", "src/research/field_reviews.py"),
    "field_review_app": ("model_study", "src/research/review_app.py"),
    "book_partitions": ("model_study", "research/preparation/book_partition_manifest.json"),
    "book_partition_builder": ("model_study", "src/research/builders/book_partitions.py"),
    "book_partition_contract": ("model_study", "src/research/book_partitions.py"),
    "cr4_candidate": ("model_study", "research/preparation/cr4_candidate_manifest.json"),
    "cr4_builder": ("model_study", "src/research/builders/cr4.py"),
    "cr4_contract": ("model_study", "src/research/cr4.py"),
    "rpt_candidate": ("model_study", "research/preparation/rpt_candidate_manifest.json"),
    "rpt_tokenizer": ("model_study", "artifacts/hf_tokenizer/tokenizer.json"),
    "rl_methods": ("model_study", "research/preparation/rl_methods.json"),
    "rl_objectives": ("model_study", "src/training/rl.py"),
    "policy_runtime": ("model_study", "src/training/policy.py"),
    "adapter_runtime": ("model_study", "src/models/adapters.py"),
    "pilot_runtime": ("model_study", "src/training/pilot.py"),
    "pilot_config": ("model_study", "configs/research/macbook_pilot.json"),
    "bookdash_sources": ("model_study", "research/preparation/bookdash_sources.json"),
    "bookdash_candidate": ("model_study", "research/preparation/bookdash_manifest.json"),
    "bookdash_builder": ("model_study", "src/research/builders/bookdash.py"),
    "denoising_runtime": ("model_study", "src/training/denoising.py"),
    "denoising_config": ("model_study", "configs/research/book_denoising.json"),
    "denoising_observations": ("model_study", "research/results/book_denoising_20261002.json"),
    "supervision_runtime": ("model_study", "src/training/supervision.py"),
    "supervision_config": ("model_study", "configs/research/book_supervision.json"),
    "recurrent_ppo_review": ("model_study", "docs/research/rnn_ppo_review.md"),
    "pilot_observations": ("model_study", "research/results/macbook_pilot_20261002.json"),
    "encoder_runtime": ("model_study", "src/models/encoder.py"),
    "feedforward_runtime": ("model_study", "src/models/feedforward.py"),
    "runtime_architecture": ("model_study", "docs/architecture.md"),
    "attention_runtime": ("model_study", "src/models/attention.py"),
    "decoder_runtime": ("model_study", "src/models/decoder.py"),
    "partial_label_loss": ("model_study", "src/models/losses.py"),
    "classification_heads": ("model_study", "src/models/heads.py"),
    "multitask_runtime": ("model_study", "src/models/multitask.py"),
    "model_factory": ("model_study", "src/models/factory.py"),
    "trainer_runtime": ("model_study", "src/training/trainer.py"),
    "training_metrics": ("model_study", "src/training/metrics.py"),
    "training_entry": ("model_study", "scripts/train.py"),
    "profile_entry": ("model_study", "scripts/profile_training.py"),
    "training_data_contract": ("model_study", "src/data/dataset.py"),
    "batch_contract": ("model_study", "src/data/dataloader.py"),
    "label_metadata_contract": ("model_study", "src/utils/labels.py"),
    "inference_contract": ("model_study", "src/inference/pipeline.py"),
    "inference_factory": ("model_study", "src/inference/factory.py"),
    "licensed_books": ("model_study", "research/preparation/licensed_books_manifest.json"),
    "licensed_book_sources": ("model_study", "research/preparation/licensed_books_sources.json"),
    "licensed_book_builder": ("model_study", "src/research/builders/licensed_books.py"),
    "book_field_sources": ("model_study", "research/preparation/book_field_sources.json"),
    "source_archive": ("archive", "docs/research/source_archive.md"),
    "dataset_decisions": ("model_study", "docs/research/dataset_decisions.md"),
    "goemotions_candidate": ("archive", "research/preparation/goemotions_candidate_manifest.json"),
    "candidate_io": ("common", "src/research/candidate_io.py"),
    "catalogue_storage": ("common", "src/catalog/storage.py"),
    "ag_news_candidate": ("archive", "research/preparation/ag_news_candidate_manifest.json"),
    "ag_news_builder": ("archive", "src/research/builders/ag_news.py"),
    "arxiv_source": ("archive", "research/preparation/arxiv_source_manifest.json"),
    "arxiv_builder": ("archive", "src/research/builders/arxiv.py"),
    "goemotions_partitions": ("archive", "research/preparation/goemotions_partition_manifest.json"),
    "ag_news_partitions": ("archive", "research/preparation/ag_news_partition_manifest.json"),
    "partition_contract": ("archive", "src/research/partitions.py"),
    "partition_builder": ("archive", "src/research/builders/source_partitions.py"),
    "goemotions_builder": ("archive", "src/research/builders/goemotions.py"),
    "compute_ledger_template": ("model_study", "research/preparation/compute_ledger_template.json"),
    "compute_contract": ("model_study", "src/research/ledger.py"),
    "compute_accounting": ("model_study", "docs/research/compute_accounting.md"),
    "model_admission_contract": ("model_study", "src/research/admission.py"),
    "model_admission_guide": ("model_study", "docs/research/admission_contracts.md"),
    "book_literature": ("book_study", "research/preparation/book_literature.json"),
    "book_methods_review": ("book_study", "docs/research/book_discovery_review.md"),
    "annotation_packet": ("book_study", "research/preparation/annotation_packet.json"),
    "catalogue_contract": ("book_study", "src/catalog/openlibrary.py"),
    "annotation_contract": ("book_study", "src/research/annotations.py"),
    "annotation_guide": ("book_study", "docs/research/annotation_preparation.md"),
    "mood_rubric": ("book_study", "docs/mood_annotation_guide.md"),
    "relevance_rubric": ("book_study", "docs/recommendation_judgments.md"),
    "book_admission_contract": ("book_study", "src/research/book_admission.py"),
    "book_admission_guide": ("book_study", "docs/research/book_admission_contract.md"),
}


def build_manifest(root: Path) -> dict[str, Any]:
    """Snapshot reviewed files. Building a snapshot does not admit their claims."""
    rows = []
    for artifact_id, (scope, relative) in ARTIFACTS.items():
        data = safe_path(root, relative).read_bytes()
        rows.append(
            {
                "id": artifact_id,
                "scope": scope,
                "path": relative,
                "bytes": len(data),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    return {
        "schema_version": 1,
        "purpose": "Research preparation evidence, not execution authority",
        "artifacts": rows,
    }
